<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->integer('id')->autoIncrement();
            $table->integer('state_id');
            $table->foreign('state_id')->references('id')->on('states');
            $table->timestamps();
        });


        DB::table('cities')->insert([
            ['id'=>1, 'state_id'=>1],
            ['id'=>2,'state_id'=> 1],
            ['id'=>3,'state_id'=> 1],
            ['id'=>4,'state_id'=> 1],
            ['id'=>5,'state_id'=> 1],
            ['id'=>6,'state_id'=> 1],
            ['id'=>7,'state_id'=> 1],
            ['id'=>8,'state_id'=> 1],
            ['id'=>9,'state_id'=> 1],
            ['id'=>10,'state_id'=> 1],
            ['id'=>11,'state_id'=> 1],
            ['id'=>12,'state_id'=> 1],
            ['id'=>13,'state_id'=> 1],
            ['id'=>14,'state_id'=> 1],
            ['id'=>15,'state_id'=> 1],
            ['id'=>16,'state_id'=> 1],
            ['id'=>17,'state_id'=> 1],
            ['id'=>18,'state_id'=> 1],
            ['id'=>19,'state_id'=> 1],
            ['id'=>20,'state_id'=> 1],
            ['id'=>21,'state_id'=> 1],
            ['id'=>22,'state_id'=> 1],
            ['id'=>23,'state_id'=> 1],
            ['id'=>24,'state_id'=> 1],
            ['id'=>25,'state_id'=> 1],
            ['id'=>26,'state_id'=> 1],
            ['id'=>27,'state_id'=> 1],
            ['id'=>28,'state_id'=> 1],
            ['id'=>29,'state_id'=> 1],
            ['id'=>30,'state_id'=> 1],
            ['id'=>31,'state_id'=> 1],
            ['id'=>32,'state_id'=> 1],
            ['id'=>33,'state_id'=> 2],
            ['id'=>34,'state_id'=> 2],
            ['id'=>35,'state_id'=> 2],
            ['id'=>36,'state_id'=> 2],
            ['id'=>37,'state_id'=> 2],
            ['id'=>38,'state_id'=> 2],
            ['id'=>39,'state_id'=> 2],
            ['id'=>40,'state_id'=> 2],
            ['id'=>41,'state_id'=> 2],
            ['id'=>42,'state_id'=> 2],
            ['id'=>43,'state_id'=> 2],
            ['id'=>44,'state_id'=> 2],
            ['id'=>45,'state_id'=> 2],
            ['id'=>46,'state_id'=> 2],
            ['id'=>47,'state_id'=> 2],
            ['id'=>48,'state_id'=> 2],
            ['id'=>49,'state_id'=> 2],
            ['id'=>50,'state_id'=> 2],
            ['id'=>51,'state_id'=> 2],
            ['id'=>52,'state_id'=> 2],
            ['id'=>53,'state_id'=> 2],
            ['id'=>54,'state_id'=> 2],
            ['id'=>55,'state_id'=> 2],
            ['id'=>56,'state_id'=> 2],
            ['id'=>57,'state_id'=> 2],
            ['id'=>58,'state_id'=> 2],
            ['id'=>59,'state_id'=> 2],
            ['id'=>60,'state_id'=> 2],
            ['id'=>61,'state_id'=> 2],
            ['id'=>62,'state_id'=> 2],
            ['id'=>63,'state_id'=> 2],
            ['id'=>64,'state_id'=> 2],
            ['id'=>65,'state_id'=> 2],
            ['id'=>66,'state_id'=> 2],
            ['id'=>67,'state_id'=> 2],
            ['id'=>68,'state_id'=> 2],
            ['id'=>69,'state_id'=> 2],
            ['id'=>70,'state_id'=> 2],
            ['id'=>71,'state_id'=> 2],
            ['id'=>72,'state_id'=> 2],
            ['id'=>73,'state_id'=> 2],
            ['id'=>74,'state_id'=> 2],
            ['id'=>75,'state_id'=> 2],
            ['id'=>76,'state_id'=> 2],
            ['id'=>77,'state_id'=> 2],
            ['id'=>78,'state_id'=> 2],
            ['id'=>79,'state_id'=> 2],
            ['id'=>80,'state_id'=> 2],
            ['id'=>81,'state_id'=> 2],
            ['id'=>82,'state_id'=> 2],
            ['id'=>83,'state_id'=> 2],
            ['id'=>84,'state_id'=> 3],
            ['id'=>85,'state_id'=> 3],
            ['id'=>86,'state_id'=> 3],
            ['id'=>87,'state_id'=> 3],
            ['id'=>88,'state_id'=> 3],
            ['id'=>89,'state_id'=> 3],
            ['id'=>90,'state_id'=> 3],
            ['id'=>91,'state_id'=> 4],
            ['id'=>92,'state_id'=> 4],
            ['id'=>93,'state_id'=> 4],
            ['id'=>94,'state_id'=> 4],
            ['id'=>95,'state_id'=> 4],
            ['id'=>96,'state_id'=> 5],
            ['id'=>97,'state_id'=> 5],
            ['id'=>98,'state_id'=> 5],
            ['id'=>99,'state_id'=> 5],
            ['id'=>100,'state_id'=> 5],
            ['id'=>101,'state_id'=> 5],
            ['id'=>102,'state_id'=> 5],
            ['id'=>103,'state_id'=> 5],
            ['id'=>104,'state_id'=> 5],
            ['id'=>105,'state_id'=> 5],
            ['id'=>106,'state_id'=> 5],
            ['id'=>107,'state_id'=> 6],
            ['id'=>108,'state_id'=> 6],
            ['id'=>109,'state_id'=> 6],
            ['id'=>110,'state_id'=> 6],
            ['id'=>111,'state_id'=> 6],
            ['id'=>112,'state_id'=> 6],
            ['id'=>113,'state_id'=> 6],
            ['id'=>114,'state_id'=> 7],
            ['id'=>115,'state_id'=> 7],
            ['id'=>116,'state_id'=> 7],
            ['id'=>117,'state_id'=> 7],
            ['id'=>118,'state_id'=> 7],
            ['id'=>119,'state_id'=> 7],
            ['id'=>120,'state_id'=> 8],
            ['id'=>121,'state_id'=> 8],
            ['id'=>122,'state_id'=> 8],
            ['id'=>123,'state_id'=> 8],
            ['id'=>124,'state_id'=> 8],
            ['id'=>125,'state_id'=> 8],
            ['id'=>126,'state_id'=> 8],
            ['id'=>127,'state_id'=> 8],
            ['id'=>128,'state_id'=> 8],
            ['id'=>129,'state_id'=> 8],
            ['id'=>130,'state_id'=> 8],
            ['id'=>131,'state_id'=> 8],
            ['id'=>132,'state_id'=> 8],
            ['id'=>133,'state_id'=> 8],
            ['id'=>134,'state_id'=> 8],
            ['id'=>135,'state_id'=> 9],
            ['id'=>136,'state_id'=> 9],
            ['id'=>137,'state_id'=> 9],
            ['id'=>138,'state_id'=> 9],
            ['id'=>139,'state_id'=> 9],
            ['id'=>140,'state_id'=> 9],
            ['id'=>141,'state_id'=> 9],
            ['id'=>142, 'state_id'=>10],
            ['id'=>143, 'state_id'=>10],
            ['id'=>144, 'state_id'=>10],
            ['id'=>145, 'state_id'=>10],
            ['id'=>146, 'state_id'=>10],
            ['id'=>147, 'state_id'=>10],
            ['id'=>148, 'state_id'=>10],
            ['id'=>149, 'state_id'=>11],
            ['id'=>150, 'state_id'=>11],
            ['id'=>151, 'state_id'=>11],
            ['id'=>152, 'state_id'=>11],
            ['id'=>153, 'state_id'=>11],
            ['id'=>154, 'state_id'=>11],
            ['id'=>155, 'state_id'=>12],
            ['id'=>156, 'state_id'=>12],
            ['id'=>157, 'state_id'=>12],
            ['id'=>158, 'state_id'=>12],
            ['id'=>159, 'state_id'=>12],
            ['id'=>160, 'state_id'=>12],
            ['id'=>161, 'state_id'=>12],
            ['id'=>162, 'state_id'=>12],
            ['id'=>163, 'state_id'=>12],
            ['id'=>164, 'state_id'=>12],
            ['id'=>165, 'state_id'=>12],
            ['id'=>166, 'state_id'=>12],
            ['id'=>167, 'state_id'=>13],
            ['id'=>168, 'state_id'=>13],
            ['id'=>169, 'state_id'=>13],
            ['id'=>170, 'state_id'=>13],
            ['id'=>171, 'state_id'=>13],
            ['id'=>172, 'state_id'=>13],
            ['id'=>173, 'state_id'=>13],
            ['id'=>174, 'state_id'=>13],
            ['id'=>175, 'state_id'=>13],
            ['id'=>176, 'state_id'=>13],
            ['id'=>177, 'state_id'=>13],
            ['id'=>178, 'state_id'=>13],
            ['id'=>179, 'state_id'=>13],
            ['id'=>180, 'state_id'=>13],
            ['id'=>181, 'state_id'=>13],
            ['id'=>182, 'state_id'=>13],
            ['id'=>183, 'state_id'=>13],
            ['id'=>184, 'state_id'=>13],
            ['id'=>185, 'state_id'=>14],
            ['id'=>186, 'state_id'=>14],
            ['id'=>187, 'state_id'=>14],
            ['id'=>188, 'state_id'=>14],
            ['id'=>189, 'state_id'=>15],
            ['id'=>190, 'state_id'=>15],
            ['id'=>191, 'state_id'=>15],
            ['id'=>192, 'state_id'=>15],
            ['id'=>193, 'state_id'=>15],
            ['id'=>194, 'state_id'=>15],
            ['id'=>195, 'state_id'=>15],
            ['id'=>196, 'state_id'=>15],
            ['id'=>197, 'state_id'=>15],
            ['id'=>198, 'state_id'=>15],
            ['id'=>199, 'state_id'=>15],
            ['id'=>200, 'state_id'=>16],
            ['id'=>201, 'state_id'=>16],
            ['id'=>202, 'state_id'=>16],
            ['id'=>203, 'state_id'=>16],
            ['id'=>204, 'state_id'=>17],
            ['id'=>205, 'state_id'=>17],
            ['id'=>206, 'state_id'=>17],
            ['id'=>207, 'state_id'=>17],
            ['id'=>208, 'state_id'=>17],
            ['id'=>209, 'state_id'=>17],
            ['id'=>210, 'state_id'=>17],
            ['id'=>211, 'state_id'=>17],
            ['id'=>212, 'state_id'=>17],
            ['id'=>213, 'state_id'=>17],
            ['id'=>214, 'state_id'=>17],
            ['id'=>215, 'state_id'=>17],
            ['id'=>216, 'state_id'=>17],
            ['id'=>217, 'state_id'=>17],
            ['id'=>218, 'state_id'=>17],
            ['id'=>219, 'state_id'=>17],
            ['id'=>220, 'state_id'=>17],
            ['id'=>221, 'state_id'=>18],
            ['id'=>222, 'state_id'=>18],
            ['id'=>223, 'state_id'=>18],
            ['id'=>224, 'state_id'=>18],
            ['id'=>225, 'state_id'=>18],
            ['id'=>226, 'state_id'=>18],
            ['id'=>227, 'state_id'=>19],
            ['id'=>228, 'state_id'=>19],
            ['id'=>229, 'state_id'=>19],
            ['id'=>230, 'state_id'=>19],
            ['id'=>231, 'state_id'=>19],
            ['id'=>232, 'state_id'=>19],
            ['id'=>233, 'state_id'=>19],
            ['id'=>234, 'state_id'=>19],
            ['id'=>235, 'state_id'=>20],
            ['id'=>236, 'state_id'=>20],
            ['id'=>237, 'state_id'=>20],
            ['id'=>238, 'state_id'=>20],
            ['id'=>239, 'state_id'=>20],
            ['id'=>240, 'state_id'=>21],
            ['id'=>241, 'state_id'=>21],
            ['id'=>242, 'state_id'=>21],
            ['id'=>243, 'state_id'=>21],
            ['id'=>244, 'state_id'=>21],
            ['id'=>245, 'state_id'=>21],
            ['id'=>246, 'state_id'=>21],
            ['id'=>247, 'state_id'=>21],
            ['id'=>248, 'state_id'=>22],
            ['id'=>249, 'state_id'=>22],
            ['id'=>250, 'state_id'=>22],
            ['id'=>251, 'state_id'=>22],
            ['id'=>252, 'state_id'=>22],
            ['id'=>253, 'state_id'=>22],
            ['id'=>254, 'state_id'=>22],
            ['id'=>255, 'state_id'=>22],
            ['id'=>256, 'state_id'=>22],
            ['id'=>257, 'state_id'=>22],
            ['id'=>258, 'state_id'=>22],
            ['id'=>259, 'state_id'=>22],
            ['id'=>260, 'state_id'=>23],
            ['id'=>261, 'state_id'=>23],
            ['id'=>262, 'state_id'=>23],
            ['id'=>263, 'state_id'=>23],
            ['id'=>264, 'state_id'=>23],
            ['id'=>265, 'state_id'=>23],
            ['id'=>266, 'state_id'=>23],
            ['id'=>267, 'state_id'=>23],
            ['id'=>268, 'state_id'=>23],
            ['id'=>269, 'state_id'=>23],
            ['id'=>270, 'state_id'=>24],
            ['id'=>271, 'state_id'=>24],
            ['id'=>272, 'state_id'=>24],
            ['id'=>273, 'state_id'=>24],
            ['id'=>274, 'state_id'=>24],
            ['id'=>275, 'state_id'=>24],
            ['id'=>276, 'state_id'=>24],
            ['id'=>277, 'state_id'=>24],
            ['id'=>278, 'state_id'=>25],
            ['id'=>279, 'state_id'=>25],
            ['id'=>280, 'state_id'=>25],
            ['id'=>281, 'state_id'=>25],
            ['id'=>282, 'state_id'=>25],
            ['id'=>283, 'state_id'=>25],
            ['id'=>284, 'state_id'=>25],
            ['id'=>285, 'state_id'=>25],
            ['id'=>286, 'state_id'=>25],
            ['id'=>287, 'state_id'=>25],
            ['id'=>288, 'state_id'=>26],
            ['id'=>289, 'state_id'=>26],
            ['id'=>290, 'state_id'=>26],
            ['id'=>291, 'state_id'=>26],
            ['id'=>292, 'state_id'=>26],
            ['id'=>293, 'state_id'=>26],
            ['id'=>294, 'state_id'=>26],
            ['id'=>295, 'state_id'=>26],
            ['id'=>296, 'state_id'=>26],
            ['id'=>297, 'state_id'=>26],
            ['id'=>298, 'state_id'=>27],
            ['id'=>299, 'state_id'=>27],
            ['id'=>300, 'state_id'=>27],
            ['id'=>301, 'state_id'=>27],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}
